stages:
  load_data:
    cmd: python src/load_data.py --config params.yaml
    deps:
      - src/load_data.py
      - src/get_data.py
      - data_given/raw_dataset.csv
    outs:
      - data/raw/raw_dataset.csv
